### ISSUE TITLE
IGzipFile should not crash on wrong compression level when opened for reading.

### ISSUE THREAD

**Issue by fjossandon** [pycompression/python-isal#187] opened 2024-02-16 20:05 UTC
Hello @rhpvorderman,
Today a colleague had an unexpected crash when making some tests with a program that we use (`Cutadapt`) while using some gzipped files, and the error was coming from the isal library. The context is Cutadapt 3.7 in Python 3.11.

Since this program has been working fine for a long time, we compared the version of the involved libraries with a previous working copy and found that previously we were using isal version 1.3.0, while the new one is version 1.5.3.

I made a test case to reproduce it. First I freshly installed cutadapt 3.7 in a virtual environment:
```
(isal) fossandon@unicron:~/Downloads/isal_bug$ pip install cutadapt==3.7
Collecting cutadapt==3.7
..........
Successfully built cutadapt
Installing collected packages: zlib-ng, isal, xopen, dnaio, cutadapt
Successfully installed cutadapt-3.7 dnaio-1.2.0 isal-1.5.3 xopen-1.9.0 zlib-ng-0.4.0
```
You can see the installed version of each package above.

Then I executed the following command:
```
$ cutadapt -a 'CCCBDGTAGTCC;max_error_rate=0.1;min_overlap=12' --output output/123_R1.fastq -A 'TTACCGCGGC;max_error_rate=0.5;min_overlap=10' --paired-output output/123_R2.fastq --pair-adapters --pair-filter any 123_S1_L001_R1_001.fastq.gz 123_S1_L001_R2_001.fastq.gz
This is cutadapt 3.7 with Python 3.11.6
Command line parameters: -a CCCBDGTAGTCC;max_error_rate=0.1;min_overlap=12 --output output/123_R1.fastq -A TTACCGCGGC;max_error_rate=0.5;min_overlap=10 --paired-output output/123_R2.fastq --pair-adapters --pair-filter any 123_S1_L001_R1_001.fastq.gz 123_S1_L001_R2_001.fastq.gz
Traceback (most recent call last):
  File "/home/fossandon/pyenvs/isal/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
             ^^^^^^^^^^
  File "/home/fossandon/pyenvs/isal/lib/python3.11/site-packages/cutadapt/__main__.py", line 965, in main_cli
    main(sys.argv[1:])
  File "/home/fossandon/pyenvs/isal/lib/python3.11/site-packages/cutadapt/__main__.py", line 1035, in main
    runner = setup_runner(
             ^^^^^^^^^^^^^
  File "/home/fossandon/pyenvs/isal/lib/python3.11/site-packages/cutadapt/__main__.py", line 1114, in setup_runner
    infiles = inpaths.open(file_opener)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fossandon/pyenvs/isal/lib/python3.11/site-packages/cutadapt/pipeline.py", line 83, in open
    file1, file2 = file_opener.xopen_pair(self.path1, self.path2, "rb")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fossandon/pyenvs/isal/lib/python3.11/site-packages/cutadapt/utils.py", line 222, in xopen_pair
    file1 = self.xopen_or_none(path1, mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fossandon/pyenvs/isal/lib/python3.11/site-packages/cutadapt/utils.py", line 214, in xopen_or_none
    return self.xopen(path, mode)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fossandon/pyenvs/isal/lib/python3.11/site-packages/cutadapt/utils.py", line 204, in xopen
    f = open_raise_limit(
        ^^^^^^^^^^^^^^^^^
  File "/home/fossandon/pyenvs/isal/lib/python3.11/site-packages/cutadapt/utils.py", line 51, in open_raise_limit
    f = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fossandon/pyenvs/isal/lib/python3.11/site-packages/xopen/__init__.py", line 1268, in xopen
    opened_file = _open_gz(
                  ^^^^^^^^^
  File "/home/fossandon/pyenvs/isal/lib/python3.11/site-packages/xopen/__init__.py", line 1071, in _open_gz
    g = _open_reproducible_gzip(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fossandon/pyenvs/isal/lib/python3.11/site-packages/xopen/__init__.py", line 1102, in _open_reproducible_gzip
    gzip_file = igzip.IGzipFile(**kwargs, compresslevel=compresslevel)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fossandon/pyenvs/isal/lib/python3.11/site-packages/isal/igzip.py", line 155, in __init__
    raise ValueError(
ValueError: Compression level should be between 0 and 3.
```
Since the error came from isal, I tested downgrading it to narrow down in which version this started to break, while keeping the other libraries' versions the same... I tested the isal versions 1.5.0, and 1.4.0 and they gave the same error, but version 1.3.0 worked!
```
(isal) fossandon@unicron:~/Downloads/isal_bug$ pip install isal==1.3.0
Collecting isal==1.3.0
  Obtaining dependency information for isal==1.3.0 from https://files.pythonhosted.org/packages/ef/ad/b8dab8bda012eeea5577f0947e4a5fcf753eb4ea165e8af293290a1beb0d/isal-1.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached isal-1.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.7 kB)
Using cached isal-1.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (250 kB)
Installing collected packages: isal
  Attempting uninstall: isal
    Found existing installation: isal 1.4.0
    Uninstalling isal-1.4.0:
      Successfully uninstalled isal-1.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xopen 1.9.0 requires isal>=1.4.1; platform_machine == "x86_64" or platform_machine == "AMD64" or platform_machine == "aarch64", but you have isal 1.3.0 which is incompatible.
Successfully installed isal-1.3.0
(isal) fossandon@unicron:~/Downloads/isal_bug$ cutadapt -a 'CCCBDGTAGTCC;max_error_rate=0.1;min_overlap=12' --output output/123_R1.fastq -A 'TTACCGCGGC;max_error_rate=0.5;min_overlap=10' --paired-output output/123_R2.fastq --pair-adapters --pair-filter any 123_S1_L001_R1_001.fastq.gz 123_S1_L001_R2_001.fastq.gz
This is cutadapt 3.7 with Python 3.11.6
Command line parameters: -a CCCBDGTAGTCC;max_error_rate=0.1;min_overlap=12 --output output/123_R1.fastq -A TTACCGCGGC;max_error_rate=0.5;min_overlap=10 --paired-output output/123_R2.fastq --pair-adapters --pair-filter any 123_S1_L001_R1_001.fastq.gz 123_S1_L001_R2_001.fastq.gz
Processing reads on 1 core in paired-end mode ...
Done           00:00:01        79,582 reads @  17.8 µs/read;   3.38 M reads/minute
Finished in 1.45 s (18 µs/read; 3.30 M reads/minute).
```
I uploaded my test files temporarily to Google Drive so you can get them to test:
https://drive.google.com/drive/folders/1NILj1b0tVdr9m_ioms4yjb_pVV2_2408?usp=sharing

I hope you can check it out!

Best regards,

**Comment by rhpvorderman** [comment] 2024-02-19 07:13
Hi @fjossandon, thanks for reporting. It might be that this bug is caused by the latest release of xopen as well, ping @marcelm . I will investigate the issue and report back my findings.

**Comment by rhpvorderman** [comment] 2024-02-19 07:21
The bug is caused by that xopen now always opens IGzipFile with a compression level, even for reading. (See https://github.com/pycompression/xopen/compare/v1.8.0...v1.9.0). Unfortunately, IGzipFile always crashes on a wrong compression level, even if opened for reading. This was not discovered during testing, as xopen has a default gzip compression level of 1. Cutadapt however uses a default of 5. Hence the bug only occurs using cutadapt. 

I think the most sane thing to do here is to not throw a compresion level error in python-isal when the gzip file is opened for reading. The compression level should be ignored when reading anyway.

Thanks for reporting. I will start working on a fix.

**Comment by rhpvorderman** [comment] 2024-02-19 08:07
I did an extra check, and python's `GzipFile` does not crash when opened in read mode with a wrong compresslevel. So this is indeed a bug here in python-isal.

While the tests were running I did a check how old this bug actually is. The line was written on August 27th 2020. That was during the birth of this library. Version 0.1.0 would only be released in November that year. So you just reported a 3.5 year old bug. Thanks for this. You will get one free beer (or other beverage) if we meet in person ;-).

**Closed** 2024-02-19 08:08 UTC

**Comment by rhpvorderman** [comment] 2024-02-19 11:10
@fjossandon The newest version 1.6.0 is released on PyPI, so the problem should be fixed now. Can you check?

**Comment by fjossandon** [comment] 2024-02-19 12:57
Hello @rhpvorderman,

> So you just reported a 3.5 year old bug. Thanks for this. You will get one free beer (or other beverage) if we meet in person ;-).

Awesome! =D

The fix worked like a charm! Thanks for it!!
```
(isal) fossandon@unicron:~/Downloads/isal_bug$ pip install isal==1.6.0
Collecting isal==1.6.0
  Obtaining dependency information for isal==1.6.0 from https://files.pythonhosted.org/packages/16/92/2311d41aa591b77b42edf621dd00e7a724fead231c80200e180d83472312/isal-1.6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading isal-1.6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.9 kB)
Downloading isal-1.6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (258 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 258.3/258.3 kB 589.7 kB/s eta 0:00:00
Installing collected packages: isal
  Attempting uninstall: isal
    Found existing installation: isal 1.5.2
    Uninstalling isal-1.5.2:
      Successfully uninstalled isal-1.5.2
Successfully installed isal-1.6.0

(isal) fossandon@unicron:~/Downloads/isal_bug$ cutadapt -a 'CCCBDGTAGTCC;max_error_rate=0.1;min_overlap=12' --output output/123_R1.fastq -A 'TTACCGCGGC;max_error_rate=0.5;min_overlap=10' --paired-output output/123_R2.fastq --pair-adapters --pair-filter any 123_S1_L001_R1_001.fastq.gz 123_S1_L001_R2_001.fastq.gz
This is cutadapt 3.7 with Python 3.11.6
Command line parameters: -a CCCBDGTAGTCC;max_error_rate=0.1;min_overlap=12 --output output/123_R1.fastq -A TTACCGCGGC;max_error_rate=0.5;min_overlap=10 --paired-output output/123_R2.fastq --pair-adapters --pair-filter any 123_S1_L001_R1_001.fastq.gz 123_S1_L001_R2_001.fastq.gz
Processing reads on 1 core in paired-end mode ...
Done           00:00:01        79,582 reads @  17.2 µs/read;   3.48 M reads/minute
Finished in 1.40 s (18 µs/read; 3.42 M reads/minute).
```
