### ISSUE TITLE
Error building wheels for isal

### ISSUE THREAD

**Issue by tkundrat** [pycompression/python-isal#195] opened 2024-05-01 21:16 UTC
Hey there, I tried to upgrade `homeassistant` today, which seems to have a dependency on `isal`.
While trying to build and install `isal` I got the following output:

<details><summary>`pip3 install --upgrade homeassistant` output</summary>
<p>

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: homeassistant in /home/pi/test-venv/lib/python3.12/site-packages (2024.4.4)
Collecting homeassistant
  Using cached homeassistant-2024.5.0-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: aiodns[...]
[...]
Collecting isal>=1.6.1 (from aiohttp-isal==0.2.0->homeassistant)
  Using cached isal-1.6.1.tar.gz (774 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: pytz[...]
[...]
Using cached homeassistant-2024.5.0-py3-none-any.whl (36.4 MB)
Building wheels for collected packages: isal
  Building wheel for isal (pyproject.toml): started
  Building wheel for isal (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for isal (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [227 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-312
      creating build/lib.linux-aarch64-cpython-312/isal
      copying src/isal/igzip_threaded.py -> build/lib.linux-aarch64-cpython-312/isal
      copying src/isal/__init__.py -> build/lib.linux-aarch64-cpython-312/isal
      copying src/isal/igzip.py -> build/lib.linux-aarch64-cpython-312/isal
      copying src/isal/igzip_lib.pyi -> build/lib.linux-aarch64-cpython-312/isal
      copying src/isal/_isal.pyi -> build/lib.linux-aarch64-cpython-312/isal
      copying src/isal/isal_zlib.pyi -> build/lib.linux-aarch64-cpython-312/isal
      copying src/isal/py.typed -> build/lib.linux-aarch64-cpython-312/isal
      creating build/lib.linux-aarch64-cpython-312/isal/isa-l
      copying src/isal/isa-l/LICENSE -> build/lib.linux-aarch64-cpython-312/isal/isa-l
      copying src/isal/isa-l/README.md -> build/lib.linux-aarch64-cpython-312/isal/isa-l
      copying src/isal/isa-l/Release_notes.txt -> build/lib.linux-aarch64-cpython-312/isal/isa-l
      running build_ext
      mkdir -p bin
      Building isa-l.h
        ---> Building erasure_code/ec_base.c  aarch64
        ---> Building raid/raid_base.c  aarch64
        ---> Building crc/crc_base.c  aarch64
        ---> Building crc/crc64_base.c  aarch64
        ---> Building igzip/igzip.c  aarch64
        ---> Building igzip/hufftables_c.c  aarch64
        ---> Building igzip/igzip_base.c  aarch64
        ---> Building igzip/igzip_icf_base.c  aarch64
        ---> Building igzip/adler32_base.c  aarch64
        ---> Building igzip/flatten_ll.c  aarch64
        ---> Building igzip/aarch64/encode_df.S  aarch64
      igzip/aarch64/encode_df.S: Assembler messages:
      igzip/aarch64/encode_df.S:32: Error: unknown architecture `armv8-a+crc'
      
      igzip/aarch64/encode_df.S:46: Warning: unknown register 'x0' -- .req ignored
      igzip/aarch64/encode_df.S:64:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:47: Warning: unknown register 'w0' -- .req ignored
      igzip/aarch64/encode_df.S:64:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:48: Warning: unknown register 'x0' -- .req ignored
      igzip/aarch64/encode_df.S:64:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:46: Warning: unknown register 'x1' -- .req ignored
      igzip/aarch64/encode_df.S:65:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:47: Warning: unknown register 'w1' -- .req ignored
      igzip/aarch64/encode_df.S:65:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:48: Warning: unknown register 'x1' -- .req ignored
      igzip/aarch64/encode_df.S:65:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:46: Warning: unknown register 'x2' -- .req ignored
      igzip/aarch64/encode_df.S:66:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:47: Warning: unknown register 'w2' -- .req ignored
      igzip/aarch64/encode_df.S:66:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:48: Warning: unknown register 'x2' -- .req ignored
      igzip/aarch64/encode_df.S:66:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:46: Warning: unknown register 'x3' -- .req ignored
      igzip/aarch64/encode_df.S:67:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:47: Warning: unknown register 'w3' -- .req ignored
      igzip/aarch64/encode_df.S:67:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:48: Warning: unknown register 'x3' -- .req ignored
      igzip/aarch64/encode_df.S:67:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:46: Warning: unknown register 'x4' -- .req ignored
      igzip/aarch64/encode_df.S:70:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:47: Warning: unknown register 'w4' -- .req ignored
      igzip/aarch64/encode_df.S:70:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:48: Warning: unknown register 'x4' -- .req ignored
      igzip/aarch64/encode_df.S:70:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:46: Warning: unknown register 'w5' -- .req ignored
      igzip/aarch64/encode_df.S:71:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:47: Warning: unknown register 'w5' -- .req ignored
      igzip/aarch64/encode_df.S:71:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:48: Warning: unknown register 'x5' -- .req ignored
      igzip/aarch64/encode_df.S:47: Warning: unknown register 'w12' -- .req ignored
      igzip/aarch64/encode_df.S:78:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:48: Warning: unknown register 'x12' -- .req ignored
      igzip/aarch64/encode_df.S:78:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:46: Warning: unknown register 'x13' -- .req ignored
      igzip/aarch64/encode_df.S:79:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:47: Warning: unknown register 'w13' -- .req ignored
      igzip/aarch64/encode_df.S:79:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:48: Warning: unknown register 'x13' -- .req ignored
      igzip/aarch64/encode_df.S:79:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:46: Warning: unknown register 'x4' -- .req ignored
      igzip/aarch64/encode_df.S:81:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:47: Warning: unknown register 'w4' -- .req ignored
      igzip/aarch64/encode_df.S:81:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:48: Warning: unknown register 'x4' -- .req ignored
      igzip/aarch64/encode_df.S:81:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:46: Warning: unknown register 'x7' -- .req ignored
      igzip/aarch64/encode_df.S:82:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:47: Warning: unknown register 'w7' -- .req ignored
      igzip/aarch64/encode_df.S:82:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:48: Warning: unknown register 'x7' -- .req ignored
      igzip/aarch64/encode_df.S:82:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:46: Warning: unknown register 'x14' -- .req ignored
      igzip/aarch64/encode_df.S:84:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:47: Warning: unknown register 'w14' -- .req ignored
      igzip/aarch64/encode_df.S:84:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:48: Warning: unknown register 'x14' -- .req ignored
      igzip/aarch64/encode_df.S:84:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:46: Warning: unknown register 'x15' -- .req ignored
      igzip/aarch64/encode_df.S:85:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:47: Warning: unknown register 'w15' -- .req ignored
      igzip/aarch64/encode_df.S:85:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:48: Warning: unknown register 'x15' -- .req ignored
      igzip/aarch64/encode_df.S:85:  Info: macro invoked from here
      igzip/aarch64/encode_df.S:94: Error: ARM register expected -- `cmp next_in,end_in'
      igzip/aarch64/encode_df.S:97: Error: bad instruction `ldp bb_out_buf,bb_out_end,[bb,offset_m_out_buf]'
      igzip/aarch64/encode_df.S:98: Error: ARM register expected -- `cmp bb_out_end,bb_out_buf'
      igzip/aarch64/encode_df.S:101: Error: ARM register expected -- `ldr bb_bit_count,[bb,offset_m_bit_count]'
      igzip/aarch64/encode_df.S:102: Error: ARM register expected -- `ldr bb_bits,[bb,offset_m_bits]'
      igzip/aarch64/encode_df.S:107: Error: ARM register expected -- `ldr bb_out_end,[bb,offset_m_out_end]'
      igzip/aarch64/encode_df.S:108: Error: ARM register expected -- `cmp bb_out_end,bb_out_buf'
      igzip/aarch64/encode_df.S:112: Error: ARM register expected -- `ldrh w_code_and_extra,[next_in]'
      igzip/aarch64/encode_df.S:113: Error: ARM register expected -- `add next_in,next_in,4'
      igzip/aarch64/encode_df.S:114: Error: ARM register expected -- `ldr w_dist_lit_table,[next_in,-4]'
      igzip/aarch64/encode_df.S:115: Error: ARM register expected -- `and code_and_extra,code_and_extra,1023'
      igzip/aarch64/encode_df.S:117: Error: ARM register expected -- `ldrh w_dist_extra,[next_in,-2]'
      igzip/aarch64/encode_df.S:118: Error: ARM register expected -- `add code_and_extra,code_and_extra,31'
      igzip/aarch64/encode_df.S:119: Error: selected processor does not support `ubfx x_dist_lit_table,x_dist_lit_table,10,9' in ARM mode
      igzip/aarch64/encode_df.S:120: Error: ARM register expected -- `add x_tmp0,hufftables,code_and_extra,lsl 2'
      igzip/aarch64/encode_df.S:121: Error: selected processor does not support `ubfx x_dist_extra,x_dist_extra,3,13' in ARM mode
      igzip/aarch64/encode_df.S:122: Error: ARM register expected -- `lsl x_dist_lit_table,x_dist_lit_table,2'
      igzip/aarch64/encode_df.S:124: Error: ARM register expected -- `ldr w_code_and_extra,[hufftables,code_and_extra,lsl 2]'
      igzip/aarch64/encode_df.S:125: Error: ARM register expected -- `add x_d_extra_bit_count,hufftables,x_dist_lit_table'
      igzip/aarch64/encode_df.S:126: Error: ARM register expected -- `ldrb w_l_length,[x_tmp0,3]'
      igzip/aarch64/encode_df.S:127: Error: ARM register expected -- `and code_and_extra,code_and_extra,0xffffff'
      igzip/aarch64/encode_df.S:128: Error: ARM register expected -- `ldrh w_code_sum,[hufftables,x_dist_lit_table]'
      igzip/aarch64/encode_df.S:129: Error: ARM register expected -- `ldrb w_d_length,[x_d_extra_bit_count,3]'
      igzip/aarch64/encode_df.S:130: Error: ARM register expected -- `add w_l_length,w_l_length,bb_bit_count'
      igzip/aarch64/encode_df.S:131: Error: ARM register expected -- `ldrb w_d_extra_bit_count,[x_d_extra_bit_count,2]'
      igzip/aarch64/encode_df.S:133: Error: ARM register expected -- `lsl x_tmp0,code_and_extra,x_bb_bit_count'
      igzip/aarch64/encode_df.S:134: Error: ARM register expected -- `add bb_bit_count,w_d_length,w_l_length'
      igzip/aarch64/encode_df.S:135: Error: ARM register expected -- `lsl x_code_sum,x_code_sum,x_l_length'
      igzip/aarch64/encode_df.S:136: Error: ARM register expected -- `orr x_code_sum,x_code_sum,x_tmp0'
      igzip/aarch64/encode_df.S:137: Error: ARM register expected -- `add w_count_sum,w_d_extra_bit_count,bb_bit_count'
      igzip/aarch64/encode_df.S:138: Error: ARM register expected -- `lsl x_bb_bit_count,x_dist_extra,x_bb_bit_count'
      igzip/aarch64/encode_df.S:140: Error: ARM register expected -- `orr x_bb_bit_count,x_bb_bit_count,bb_bits'
      igzip/aarch64/encode_df.S:141: Error: ARM register expected -- `orr x_tmp0,x_code_sum,x_bb_bit_count'
      igzip/aarch64/encode_df.S:142: Error: ARM register expected -- `str x_tmp0,[bb,offset_m_bits]'
      igzip/aarch64/encode_df.S:143: Error: ARM register expected -- `str w_count_sum,[bb,offset_m_bit_count]'
      igzip/aarch64/encode_df.S:145: Error: ARM register expected -- `str x_tmp0,[bb_out_buf]'
      igzip/aarch64/encode_df.S:146: Error: ARM register expected -- `ldr bb_bit_count,[bb,offset_m_bit_count]'
      igzip/aarch64/encode_df.S:147: Error: ARM register expected -- `ldr bb_bits,[bb,offset_m_bits]'
      igzip/aarch64/encode_df.S:148: Error: ARM register expected -- `and w_tmp0,bb_bit_count,-8'
      igzip/aarch64/encode_df.S:149: Error: ARM register expected -- `ldr bb_out_buf,[bb,offset_m_out_buf]'
      igzip/aarch64/encode_df.S:150: Error: ARM register expected -- `lsr w_tmp1,bb_bit_count,3'
      igzip/aarch64/encode_df.S:151: Error: ARM register expected -- `lsr bb_bits,bb_bits,x_tmp0'
      igzip/aarch64/encode_df.S:152: Error: ARM register expected -- `sub bb_bit_count,bb_bit_count,w_tmp0'
      igzip/aarch64/encode_df.S:153: Error: ARM register expected -- `add bb_out_buf,bb_out_buf,x_tmp1'
      igzip/aarch64/encode_df.S:154: Error: ARM register expected -- `str bb_bits,[bb,offset_m_bits]'
      igzip/aarch64/encode_df.S:155: Error: ARM register expected -- `str bb_bit_count,[bb,offset_m_bit_count]'
      igzip/aarch64/encode_df.S:156: Error: ARM register expected -- `str bb_out_buf,[bb,offset_m_out_buf]'
      igzip/aarch64/encode_df.S:158: Error: ARM register expected -- `cmp end_in,next_in'
      igzip/aarch64/encode_df.S:162: Error: bad instruction `ret'
        ---> Building igzip/igzip_icf_body.c  aarch64
      make: *** [make.inc:245: bin/encode_df.o] Error 1
      make: *** Waiting for unfinished jobs....
      building 'isal.isal_zlib' extension
      creating build/temp.linux-aarch64-cpython-312
      creating build/temp.linux-aarch64-cpython-312/src
      creating build/temp.linux-aarch64-cpython-312/src/isal
      gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/tmp/tmpcwgb_tqm -I/home/pi/test-venv/include -I/usr/local/include/python3.12 -c src/isal/isal_zlibmodule.c -o build/temp.linux-aarch64-cpython-312/src/isal/isal_zlibmodule.o
      src/isal/isal_zlibmodule.c: In function ‘ParallelCompress__new__’:
      src/isal/isal_zlibmodule.c:323:21: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘int’} and ‘unsigned int’ [-Wsign-compare]
        323 |     if (buffer_size > UINT32_MAX) {
            |                     ^
      src/isal/isal_zlibmodule.c: In function ‘ParallelCompress_compress_and_crc’:
      src/isal/isal_zlibmodule.c:399:30: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘int’} and ‘unsigned int’ [-Wsign-compare]
        399 |     if (data.len + zdict.len > UINT32_MAX) {
            |                              ^
      In file included from /usr/local/include/python3.12/Python.h:39,
                       from src/isal/isal_shared.h:23,
                       from src/isal/isal_zlibmodule.c:27:
      src/isal/isal_zlibmodule.c: In function ‘GzipReader_read_into_buffer’:
      /usr/local/include/python3.12/pymacro.h:27:28: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
         27 | #define Py_MIN(x, y) (((x) > (y)) ? (y) : (x))
            |                            ^
      src/isal/isal_zlibmodule.c:1756:44: note: in expansion of macro ‘Py_MIN’
       1756 |                     self->state.avail_in = Py_MIN((buffer_end -current_pos), UINT32_MAX);
            |                                            ^~~~~~
      /usr/local/include/python3.12/pymacro.h:27:43: warning: operand of ‘?:’ changes signedness from ‘int’ to ‘unsigned int’ due to unsignedness of other operand [-Wsign-compare]
         27 | #define Py_MIN(x, y) (((x) > (y)) ? (y) : (x))
            |                                           ^~~
      src/isal/isal_zlibmodule.c:1756:44: note: in expansion of macro ‘Py_MIN’
       1756 |                     self->state.avail_in = Py_MIN((buffer_end -current_pos), UINT32_MAX);
            |                                            ^~~~~~
      gcc -shared build/temp.linux-aarch64-cpython-312/src/isal/isal_zlibmodule.o /tmp/tmpcwgb_tqm/bin/isa-l.a -o build/lib.linux-aarch64-cpython-312/isal/isal_zlib.cpython-312-arm-linux-gnueabihf.so
      /usr/bin/ld: cannot find /tmp/tmpcwgb_tqm/bin/isa-l.a: No such file or directory
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for isal
Failed to build isal
ERROR: Could not build wheels for isal, which is required to install pyproject.toml-based projects
```

</p>
</details> 

Is there maybe an issue with 32/64 bit? I'm running `Raspbian GNU/Linux 12 (bookworm) aarch64`, so kernel wise there should not be an issue. Maybe something to do with my python installation, or something else?

Thanks in advance for any help!

**Comment by jan666** [comment] 2024-05-02 12:53
I tried to build it manually on my Raspberry Pi 4 (Linux pi4 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux, Raspbian 12.5/Bookworm) and it works:

```
git clone https://github.com/pycompression/python-isal.git
cd python-isal
git submodule update --init --recursive
pip install .
```

```
Processing /home/pi/python-isal
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: isal
  Building wheel for isal (pyproject.toml) ... done
  Created wheel for isal: filename=isal-1.7.0.dev0-cp311-cp311-linux_aarch64.whl size=294199 sha256=161f31f9e50167aaa9d3c8d27bbdb1f35e566b3546a90bb116004a6ea5267af0
  Stored in directory: /home/pi/.cache/pip/wheels/b2/90/b9/870714573c96eb7b73cc4ec4c2cfbd2ebbd3a4bce83f8cf1cc
Successfully built isal
Installing collected packages: isal
Successfully installed isal-1.7.0.dev0
```

I had trouble updating homeassistant on FreeBSD because of python-isal and fixed it by manually installing pysthon-isal.

**Comment by gdt** [comment] 2024-05-02 14:23
@jan666 Did your 'manually installing' require the changes in your PR?   I tried installing via pip from the sources on NetBSD and started down the same path as your PR.

**Comment by gdt** [comment] 2024-05-02 14:23
Also, were is the need to deal with submodules documented?  I don't see it in the README.

**Comment by jan666** [comment] 2024-05-02 14:28
> @jan666 Did your 'manually installing' require the changes in your PR?

Yes, but only only feeebsd. On my Raspberry Pi it works without changes. Clone, init submodule, pip install

**Comment by tkundrat** [comment] 2024-05-02 19:23
> I tried to build it manually on my Raspberry Pi 4 (Linux pi4 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux, Raspbian 12.5/Bookworm) and it works:
> 
> ```
> git clone https://github.com/pycompression/python-isal.git
> cd python-isal
> git submodule update --init --recursive
> pip install .
> ```
> 
> ```
> Processing /home/pi/python-isal
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Building wheels for collected packages: isal
>   Building wheel for isal (pyproject.toml) ... done
>   Created wheel for isal: filename=isal-1.7.0.dev0-cp311-cp311-linux_aarch64.whl size=294199 sha256=161f31f9e50167aaa9d3c8d27bbdb1f35e566b3546a90bb116004a6ea5267af0
>   Stored in directory: /home/pi/.cache/pip/wheels/b2/90/b9/870714573c96eb7b73cc4ec4c2cfbd2ebbd3a4bce83f8cf1cc
> Successfully built isal
> Installing collected packages: isal
> Successfully installed isal-1.7.0.dev0
> ```
> 
> I had trouble updating homeassistant on FreeBSD because of python-isal and fixed it by manually installing python-isal. Maybe try the same?

I tried your steps of cloning the git repo and then installing that version. I still get the same error message from the assembly compiler

**Comment by gdt** [comment] 2024-05-02 19:31
The issue is
```
igzip/aarch64/encode_df.S: Assembler messages:
igzip/aarch64/encode_df.S:32: Error: unknown architecture `armv8-a+crc'
```

and the architecture `armv8-a+crc` looks unusual to me.

I would suggest  that you get the isal library to build, separately from the python wrapper, and also see if Debian is using a different architecture value than what others expect.   But, looking at your uname, aarch64 looks normal and perhaps the isal build is adding the rest.

**Comment by tkundrat** [comment] 2024-05-02 20:19
I `git clone`d the isa-l library from intel and tried to build it. However I get this issue:
```
make --no-print-directory all-am
  CC       erasure_code/aarch64/ec_aarch64_dispatcher.lo
In file included from erasure_code/aarch64/ec_aarch64_dispatcher.c:29:
./include/aarch64_multibinary.h:32:2: error: #error "This file is for aarch64 only"
   32 | #error "This file is for aarch64 only"
      |  ^~~~~
erasure_code/aarch64/ec_aarch64_dispatcher.c: In function ‘gf_vect_dot_prod_dispatcher’:
erasure_code/aarch64/ec_aarch64_dispatcher.c:36:22: error: ‘HWCAP_SVE’ undeclared (first use in this function); did you mean ‘HWCAP_SWP’?
   36 |         if (auxval & HWCAP_SVE)
      |                      ^~~~~~~~~
      |                      HWCAP_SWP
erasure_code/aarch64/ec_aarch64_dispatcher.c:36:22: note: each undeclared identifier is reported only once for each function it appears in
erasure_code/aarch64/ec_aarch64_dispatcher.c:38:22: error: ‘HWCAP_ASIMD’ undeclared (first use in this function)
   38 |         if (auxval & HWCAP_ASIMD)
      |                      ^~~~~~~~~~~
erasure_code/aarch64/ec_aarch64_dispatcher.c: In function ‘gf_vect_mad_dispatcher’:
erasure_code/aarch64/ec_aarch64_dispatcher.c:54:22: error: ‘HWCAP_SVE’ undeclared (first use in this function); did you mean ‘HWCAP_SWP’?
   54 |         if (auxval & HWCAP_SVE)
      |                      ^~~~~~~~~
      |                      HWCAP_SWP
erasure_code/aarch64/ec_aarch64_dispatcher.c:56:22: error: ‘HWCAP_ASIMD’ undeclared (first use in this function)
   56 |         if (auxval & HWCAP_ASIMD)
      |                      ^~~~~~~~~~~
erasure_code/aarch64/ec_aarch64_dispatcher.c: In function ‘ec_encode_data_dispatcher’:
erasure_code/aarch64/ec_aarch64_dispatcher.c:72:22: error: ‘HWCAP_SVE’ undeclared (first use in this function); did you mean ‘HWCAP_SWP’?
   72 |         if (auxval & HWCAP_SVE)
      |                      ^~~~~~~~~
      |                      HWCAP_SWP
erasure_code/aarch64/ec_aarch64_dispatcher.c:74:22: error: ‘HWCAP_ASIMD’ undeclared (first use in this function)
   74 |         if (auxval & HWCAP_ASIMD)
      |                      ^~~~~~~~~~~
erasure_code/aarch64/ec_aarch64_dispatcher.c: In function ‘ec_encode_data_update_dispatcher’:
erasure_code/aarch64/ec_aarch64_dispatcher.c:90:22: error: ‘HWCAP_SVE’ undeclared (first use in this function); did you mean ‘HWCAP_SWP’?
   90 |         if (auxval & HWCAP_SVE)
      |                      ^~~~~~~~~
      |                      HWCAP_SWP
erasure_code/aarch64/ec_aarch64_dispatcher.c:92:22: error: ‘HWCAP_ASIMD’ undeclared (first use in this function)
   92 |         if (auxval & HWCAP_ASIMD)
      |                      ^~~~~~~~~~~
erasure_code/aarch64/ec_aarch64_dispatcher.c: In function ‘gf_vect_mul_dispatcher’:
erasure_code/aarch64/ec_aarch64_dispatcher.c:108:22: error: ‘HWCAP_SVE’ undeclared (first use in this function); did you mean ‘HWCAP_SWP’?
  108 |         if (auxval & HWCAP_SVE)
      |                      ^~~~~~~~~
      |                      HWCAP_SWP
erasure_code/aarch64/ec_aarch64_dispatcher.c:110:22: error: ‘HWCAP_ASIMD’ undeclared (first use in this function)
  110 |         if (auxval & HWCAP_ASIMD)
      |                      ^~~~~~~~~~~
make[1]: *** [Makefile:3766: erasure_code/aarch64/ec_aarch64_dispatcher.lo] Error 1
make: *** [Makefile:2352: all] Error 2
```
It looks like there is a compiler error because `"This file is for aarch64 only"`, but I am running an `aarch64` kernel. How can that be?

**Comment by gdt** [comment] 2024-05-02 23:24
You are missing that the `#error` could be due to some ifdef, and confusion about flavors of aarch64.

**Comment by rhpvorderman** [comment] 2024-05-03 07:42
> Hey there, I tried to upgrade homeassistant today, which seems to have a dependency on isal.

Please contact home assistent. They should not have added such a niche library without due dilligence. ISA-L is an assembly library, as such it only works on select systems. It does not work on Mac OS arm64 for instance, which is quite a substantial user base at this point. If home assistent claims to support BSD they should make sure they do not list dependencies that only support Windows, Macos and Linux. 

That said, I don't mind PRs which enable installation on BSD platforms. It is just that I cannot test those, so I will not call it "support". Also if the home assistent developers want to support BSD and they want to use a particular dependency, the responsibility is on them to ensure that this dependency works on the supported platforms, or that fallback measures are taken so that it is not automatically installed on platforms for which there is no support.

**Comment by jan666** [comment] 2024-05-03 07:49
Home Assistant does not support FreeBSD. That's why I tried fixing it myself. 

@tkundrat has no problem with FreeBSD but with Linux on his Raspberry Pi (which works for me without changes)

**Comment by tkundrat** [comment] 2024-05-03 08:07
> > Hey there, I tried to upgrade homeassistant today, which seems to have a dependency on isal.
> 
> Please contact home assistent. They should not have added such a niche library without due dilligence. ISA-L is an assembly library, as such it only works on select systems. It does not work on Mac OS arm64 for instance, which is quite a substantial user base at this point. If home assistent claims to support BSD they should make sure they do not list dependencies that only support Windows, Macos and Linux. 
> 
> That said, I don't mind PRs which enable installation on BSD platforms. It is just that I cannot test those, so I will not call it "support". Also if the home assistent developers want to support BSD and they want to use a particular dependency, the responsibility is on them to ensure that this dependency works on the supported platforms, or that fallback measures are taken so that it is not automatically installed on platforms for which there is no support.

I looked it up, they only officially support Windows, macOS and Linux installations. So this should not be an issue.
I am running a Linux based installation (RaspberryPi OS/Debian) on my 64bit RasPi 4B, so isal should be supported

**Comment by rhpvorderman** [comment] 2024-05-03 08:11
Ah sorry, due to all the BSD work going on I made some wrong assumptions. Sorry for that. 

That is quite strange. It should be able to find the wheel and install that. Could you try and see what happens when you install the wheel directly? 

For python 3.12 it should be this one: https://files.pythonhosted.org/packages/ec/25/cf5a18c06a668ee63c33d21e3a902592c6a4418b383938f0973b93761c31/isal-1.6.1-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl

Simply do `pip install  pip install https://files.pythonhosted.org/packages/ec/25/cf5a18c06a668ee63c33d21e3a902592c6a4418b383938f0973b93761c31/isal-1.6.1-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl`

Other wheels can be found here: 
https://pypi.org/project/isal/#files

**Comment by rhpvorderman** [comment] 2024-05-03 08:28
Please also provide the output of `python3 -c "import platform; print(platform.machine())"`

**Comment by tkundrat** [comment] 2024-05-03 11:59
```
$ python3

Python 3.12.2 (main, Apr 19 2024, 11:23:53) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'aarch64'
```

**Comment by rhpvorderman** [comment] 2024-05-03 12:27
Have you tried installing the wheel directly?

**Comment by tkundrat** [comment] 2024-05-03 15:32
> Have you tried installing the wheel directly?

Sorry, I did not see that message. Trying it out I get an error:
```
$ pip install https://files.pythonhosted.org/packages/ec/25/cf5a18c06a668ee63c33d21e3a902592c6a4418b383938f0973b93761c31/isal-1.6.1-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: isal-1.6.1-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl is not a supported wheel on this platform.
```

**Comment by tkundrat** [comment] 2024-05-03 15:36
Also I read through the complete changelog and they added `aiohttp-isal` just in this new release `homeassistant==2024.5.0` from 1st May. I checked, and until one version before (`2024.4.4`, the one I'm currently running) they used `aiohttp-zlib-ng` (and `zlib-ng`), so everything was fine for me.

**Comment by rhpvorderman** [comment] 2024-05-06 08:37
> ERROR: isal-1.6.1-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl is not a supported wheel on this platform.

I am affraid I cannot help with that error. For some reason your platform is not "default" aarch64 that is supported by the PyPA wheelbuilding process. As a result I cannot offer any help. I seeHomeAssistent has merged a change now where ISA-L and zlib-ng will be used as fallback options, so in the coming releases you shouldn't have any issues anymore.

**Closed by rhpvorderman** 2024-05-06 08:37 UTC
